/**
 * brandingTheme.js
 *
 * Utilities for generating, injecting, caching, uploading, and loading
 * tenant branding theme CSS.
 *
 * Theme application strategy — zero CloudFront delay
 * ───────────────────────────────────────────────────
 * The theme CSS text is stored in sessionStorage under 'tp_theme_css'.
 * On every page load App.jsx reads it synchronously and injects it before
 * React even mounts — so there is never a flash of the default theme for
 * returning visitors within the same session.
 *
 * On first login (empty cache) App.jsx fires a background fetch of
 * GET /api/tenant → GET /api/tenant/branding/css, then caches the result.
 * Subsequent navigations (SPA route changes) are instant — no fetch needed.
 *
 * On publish, Settings.jsx caches the freshly-generated CSS immediately so
 * the next navigation (or page refresh) also reflects the new theme
 * without any network call.
 *
 * The <style id="tenant-theme"> tag sets CSS vars consumed by Sidebar and
 * any other elements that use var(--brand-primary) directly.
 *
 * The Topbar reads its colours from BrandingContext (React state), which is
 * initialised from the same sessionStorage cache and updated only on Publish.
 * This means picker changes in BrandingPanel have zero effect on the live
 * portal chrome — they update only the self-contained preview widget.
 */

const API          = `${import.meta.env.VITE_API_URL ?? 'http://localhost:3000'}/api`
const STYLE_TAG_ID = 'tenant-theme'
const CACHE_KEY    = 'tp_theme_css'

// ── Colour palette ────────────────────────────────────────────────────────────

export const THEME_COLORS = [
  { id: 'forest',   label: 'Forest Green',  primary: '#3d7a28', primaryHover: '#2f6020' },
  { id: 'midnight', label: 'Midnight Blue', primary: '#1e3a8a', primaryHover: '#162d6e' },
  { id: 'crimson',  label: 'Crimson Red',   primary: '#b91c1c', primaryHover: '#991b1b' },
  { id: 'charcoal', label: 'Charcoal',      primary: '#374151', primaryHover: '#1f2937' },
  { id: 'slate',    label: 'Slate Blue',    primary: '#475569', primaryHover: '#334155' },
  { id: 'indigo',   label: 'Indigo',        primary: '#4338ca', primaryHover: '#3730a3' },
  { id: 'teal',     label: 'Teal',          primary: '#0f766e', primaryHover: '#0d6360' },
  { id: 'amber',    label: 'Amber',         primary: '#b45309', primaryHover: '#92400e' },
  { id: 'rose',     label: 'Rose',          primary: '#be123c', primaryHover: '#9f1239' },
  { id: 'custom',   label: 'Custom…',       primary: '',        primaryHover: '' },
]

/** Darken a hex colour by ~12% to derive a hover shade. */
export function deriveHover(hex) {
  const c = hex.replace('#', '')
  if (c.length !== 6) return hex
  const darken = (ch) => Math.max(0, parseInt(ch, 16) - 30).toString(16).padStart(2, '0')
  return `#${darken(c.slice(0, 2))}${darken(c.slice(2, 4))}${darken(c.slice(4, 6))}`
}

// ── CSS generation ────────────────────────────────────────────────────────────

export function generateThemeCss({ primary, primaryHover, logoUrl, tenantId, timestamp }) {
  const logoLine = logoUrl
    ? `  --brand-logo-url:   url('${logoUrl}');`
    : `  --brand-logo-url:   none;`
  return [
    `/* theme.tenant.${timestamp}.css`,
    ` * Tenant : ${tenantId}`,
    ` * Published: ${new Date(timestamp).toISOString()}`,
    ` * Generated by DMS tenant portal — do not edit manually. */`,
    `:root {`,
    `  --brand-primary:   ${primary};`,
    `  --brand-primary-h: ${primaryHover};`,
    `  --brand-on-primary:#ffffff;`,
    logoLine,
    `  --accent:   var(--brand-primary);`,
    `  --accent-h: var(--brand-primary-h);`,
    `}`,
  ].join('\n') + '\n'
}

// ── DOM injection ──────────────────────────────────────────────────────────────
//
// Operates on <style id="tenant-theme">.
// Called only on: session restore (App.jsx IIFE) and successful Publish.
// Never called on picker change.

/** Inject (or replace) the tenant theme <style> tag in <head>. */
export function injectTheme(cssText) {
  let tag = document.getElementById(STYLE_TAG_ID)
  if (!tag) {
    tag = document.createElement('style')
    tag.id = STYLE_TAG_ID
    document.head.appendChild(tag)
  }
  tag.textContent = cssText
}

/** Remove the tenant theme <style> tag (reverts to base theme). */
export function removeTheme() {
  const tag = document.getElementById(STYLE_TAG_ID)
  if (tag) tag.remove()
}

// ── sessionStorage cache ──────────────────────────────────────────────────────

/** Write theme CSS text into sessionStorage. Called after publish and after fetch. */
export function cacheThemeCss(cssText) {
  try { sessionStorage.setItem(CACHE_KEY, cssText) } catch { /* non-fatal */ }
}

/** Read cached theme CSS text. Returns null if nothing is cached. */
export function getCachedThemeCss() {
  try { return sessionStorage.getItem(CACHE_KEY) || null } catch { return null }
}

/** Clear the cached theme (called on logout). */
export function clearThemeCache() {
  try { sessionStorage.removeItem(CACHE_KEY) } catch { /* non-fatal */ }
}

// ── Upload ──────────────────────────────────────────────────────────────────

function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload  = () => resolve(reader.result.split(',')[1])
    reader.onerror = () => reject(new Error('Failed to read logo file'))
    reader.readAsDataURL(file)
  })
}

export async function uploadTheme(cssText, filename, logoFile, idToken) {
  const body = { css_text: cssText, filename }
  if (logoFile) {
    body.logo_b64       = await fileToBase64(logoFile)
    body.logo_mime_type = logoFile.type || 'image/png'
    body.logo_filename  = logoFile.name
  }
  const res = await fetch(`${API}/tenant/branding`, {
    method:  'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${idToken}` },
    body:    JSON.stringify(body),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err.detail ?? `Upload failed (HTTP ${res.status})`)
  }
  return res.json()   // { css_file, logo_url }
}

// ── Boot loader ──────────────────────────────────────────────────────────────

export async function loadTenantTheme(cssFile, idToken) {
  if (!cssFile) return
  try {
    const res = await fetch(
      `${API}/tenant/branding/css?file=${encodeURIComponent(cssFile)}`,
      { headers: { Authorization: `Bearer ${idToken}` } }
    )
    if (!res.ok) return
    const cssText = await res.text()
    cacheThemeCss(cssText)
    injectTheme(cssText)
  } catch { /* non-fatal */ }
}

// ── Private CSS-text parsers ───────────────────────────────────────────────────
// (kept for uploadTheme — no longer used by BrandingPanel)

function _extractValue(cssText, prop) {
  for (const line of cssText.split('\n')) {
    const s = line.trim()
    if (s.startsWith(prop) && !s.includes('var(')) {
      return s.replace(prop, '').replace(/;$/, '').trim()
    }
  }
  return ''
}
export function extractPrimary(cssText)      { return _extractValue(cssText, '--brand-primary:') }
export function extractPrimaryHover(cssText) { return _extractValue(cssText, '--brand-primary-h:') }
