/**
 * brandingTheme.js
 *
 * Utilities for generating, injecting, uploading, and loading tenant
 * branding theme CSS files.
 *
 * Upload protocol: JSON (not multipart/form-data).
 * API Gateway v2 + Lambda (Mangum) can silently corrupt or fail to parse
 * multipart bodies without extra binary media type configuration.  Sending
 * plain JSON avoids the issue entirely — the logo is base64-encoded in the
 * browser and decoded server-side before writing to S3.
 */

const API = `${import.meta.env.VITE_API_URL ?? 'http://localhost:3000'}/api`
const STYLE_TAG_ID = 'tenant-theme'

// ── Colour palette ────────────────────────────────────────────────────────────

export const THEME_COLORS = [
  { id: 'forest',   label: 'Forest Green',  primary: '#3d7a28', primaryHover: '#2f6020' },
  { id: 'midnight', label: 'Midnight Blue', primary: '#1e3a8a', primaryHover: '#162d6e' },
  { id: 'crimson',  label: 'Crimson Red',   primary: '#b91c1c', primaryHover: '#991b1b' },
  { id: 'charcoal', label: 'Charcoal',      primary: '#374151', primaryHover: '#1f2937' },
  { id: 'slate',    label: 'Slate Blue',    primary: '#475569', primaryHover: '#334155' },
  { id: 'indigo',   label: 'Indigo',        primary: '#4338ca', primaryHover: '#3730a3' },
  { id: 'teal',     label: 'Teal',          primary: '#0f766e', primaryHover: '#0d6360' },
  { id: 'amber',    label: 'Amber',         primary: '#b45309', primaryHover: '#92400e' },
  { id: 'rose',     label: 'Rose',          primary: '#be123c', primaryHover: '#9f1239' },
  { id: 'custom',   label: 'Custom…',       primary: '',        primaryHover: '' },
]

/** Darken a hex colour by ~12% to derive a hover shade. */
export function deriveHover(hex) {
  const c = hex.replace('#', '')
  if (c.length !== 6) return hex
  const darken = (ch) => Math.max(0, parseInt(ch, 16) - 30).toString(16).padStart(2, '0')
  return `#${darken(c.slice(0,2))}${darken(c.slice(2,4))}${darken(c.slice(4,6))}`
}

// ── CSS generation ────────────────────────────────────────────────────────────

export function generateThemeCss({ primary, primaryHover, logoUrl, tenantId, timestamp }) {
  const logoLine = logoUrl
    ? `  --brand-logo-url:   url('${logoUrl}');`
    : `  --brand-logo-url:   none;`
  return [
    `/* theme.tenant.${timestamp}.css`,
    ` * Tenant : ${tenantId}`,
    ` * Published: ${new Date(timestamp).toISOString()}`,
    ` * Generated by DMS tenant portal — do not edit manually. */`,
    `:root {`,
    `  --brand-primary:   ${primary};`,
    `  --brand-primary-h: ${primaryHover};`,
    `  --brand-on-primary:#ffffff;`,
    logoLine,
    `  --accent:   var(--brand-primary);`,
    `  --accent-h: var(--brand-primary-h);`,
    `}`,
  ].join('\n') + '\n'
}

// ── Live preview ──────────────────────────────────────────────────────────────

export function injectTheme(cssText) {
  let tag = document.getElementById(STYLE_TAG_ID)
  if (!tag) {
    tag = document.createElement('style')
    tag.id = STYLE_TAG_ID
    document.head.appendChild(tag)
  }
  tag.textContent = cssText
}

export function removeTheme() {
  const tag = document.getElementById(STYLE_TAG_ID)
  if (tag) tag.remove()
}

// ── Upload ────────────────────────────────────────────────────────────────────

/**
 * Read a File object as a base64 string.
 */
function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload  = () => {
      // result is "data:<mime>;base64,<data>" — strip the prefix
      resolve(reader.result.split(',')[1])
    }
    reader.onerror = () => reject(new Error('Failed to read logo file'))
    reader.readAsDataURL(file)
  })
}

/**
 * Upload theme CSS and optional logo to the backend as JSON.
 *
 * The logo File is base64-encoded in the browser before sending.
 * The backend decodes it and writes it to S3.
 *
 * @param {string}    cssText  - content of the theme CSS file
 * @param {string}    filename - e.g. 'theme.tenant.1715640000000.css'
 * @param {File|null} logoFile - browser File object, or null if unchanged
 * @param {string}    idToken  - Cognito ID token for Authorization header
 * @returns {Promise<{ css_file: string, logo_url: string }>}
 */
export async function uploadTheme(cssText, filename, logoFile, idToken) {
  const body = { css_text: cssText, filename }

  if (logoFile) {
    body.logo_b64       = await fileToBase64(logoFile)
    body.logo_mime_type = logoFile.type || 'image/png'
    body.logo_filename  = logoFile.name
  }

  const res = await fetch(`${API}/tenant/branding`, {
    method:  'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization:  `Bearer ${idToken}`,
    },
    body: JSON.stringify(body),
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err.detail ?? `Upload failed (HTTP ${res.status})`)
  }
  return res.json()   // { css_file, logo_url }
}

// ── Boot loader ───────────────────────────────────────────────────────────────

/**
 * Fetch the tenant's published theme CSS from the backend and inject it.
 * Called once at app boot after the session is hydrated.
 */
export async function loadTenantTheme(cssFile, idToken) {
  if (!cssFile) return
  try {
    const res = await fetch(
      `${API}/tenant/branding/css?file=${encodeURIComponent(cssFile)}`,
      { headers: { Authorization: `Bearer ${idToken}` } }
    )
    if (!res.ok) return
    injectTheme(await res.text())
  } catch {
    // Non-fatal — fall back to base theme
  }
}
